# full_panorama is a full configuration file using jinja
# this is a complete Panorama and reference device-group and template stack configuration
# this is based on a 'shared model' with all device-group elements in Shared
# this is based on a 'shared model' with all template elements in the 'iron-skillet' template

# snippet folder name
name: skillet_full_panorama_v91
# label used for menu selection
label: v9.1 Iron-Skillet for Panorama (Shared Values)
description: Iron-Skillet baseline configuration for Panorama with device-group and stack specific values
# type of device configuration
type: template
extends:

# grouping of like snippets for dynamic menu creation in pan-cnc
labels:
  service_type: iron_skillet_full
  template_category: panorama_full
  collection:
    - IronSkillet
    - Configure
    - Best Practice

# variables used in the configuration templates
# type_hint defines the form field type in pan-cnc
variables:
  - name: PANORAMA_NAME
    description: Panorama hostname
    default: panorama01
    type_hint: text
  - name: PANORAMA_TYPE
    description: Panorama management IP type
    default: static
    type_hint: dropdown
    help_text: select static unless panorama is cloud deployed and uses DHCP addressing
    dd_list:
      - key: static
        value: static
      - key: cloud dhcp
        value: cloud
  - name: PANORAMA_IP
    description: Panorama IP
    default: 192.168.1.252
    type_hint: ip_address
    toggle_hint:
      source: PANORAMA_TYPE
      value: static
  - name: PANORAMA_MASK
    description: Panorama netmask
    default: 255.255.255.0
    type_hint: ip_address
    toggle_hint:
      source: PANORAMA_TYPE
      value: static
  - name: PANORAMA_DG
    description: Panorama default gateway
    default: 192.168.55.2
    type_hint: ip_address
    toggle_hint:
      source: PANORAMA_TYPE
      value: static
  - name: CONFIG_EXPORT_IP
    description: IP address for scheduled config exports
    default: 192.0.2.3
    type_hint: text
  - name: STACK
    description: Template stack name for Panorama
    default: sample_stack
    type_hint: text
    help_text: creates a sample template stack with IronSkillet configuration elements
  - name: DEVICE_GROUP
    description: Device-group name for Panorama
    default: sample_devicegroup
    type_hint: text
    help_text: creates a sample device-group with IronSkillet configuration elements
  - name: FW_NAME
    description: Device Name for NGFW
    default: sample
    type_hint: text
  - name: MGMT_TYPE
    description: firewall management IP type
    default: dhcp-client
    type_hint: dropdown
    dd_list:
      - key: dhcp-client
        value: dhcp-client
      - key: static
        value: static
  - name: MGMT_IP
    description: NGFW management IP
    default: 192.0.2.6
    type_hint: ip_address
    toggle_hint:
      source: MGMT_TYPE
      value: static
  - name: MGMT_MASK
    description: NGFW management netmask
    type_hint: ip_address
    default: 255.255.255.0
    toggle_hint:
      source: MGMT_TYPE
      value: static
  - name: MGMT_DG
    description: NGFW management default gateway
    default: 192.0.2.7
    type_hint: ip_address
    toggle_hint:
      source: MGMT_TYPE
      value: static
  - name: NTP_1
    description: primary NTP server
    default: 0.pool.ntp.org
    type_hint: text
  - name: NTP_2
    description: secondary NTP server
    default: 1.pool.ntp.org
    type_hint: text
  - name: ADMINISTRATOR_USERNAME
    description: admin username
    default: admin
    type_hint: text
  - name: ADMINISTRATOR_PASSWORD
    description: admin password
    default: admin
    type_hint: password
  - name: DNS_1
    description: primary dns server
    default: 8.8.8.8
    type_hint: ip_address
  - name: DNS_2
    description: secondary dns server
    default: 8.8.4.4
    type_hint: ip_address
  - name: SINKHOLE_IPV4
    description: sinkhole FQDN IPv4
    default: sinkhole.paloaltonetworks.com
    type_hint: text
    help_text: FQDN value for the IPV4 sinkhole address used in the anti-spyware security profile
  - name: SINKHOLE_IPV6
    description: sinkhole address IPv6
    default: 2600:5200::1
    type_hint: ip_address
    help_text: IP address for the IPv6 sinkhole used in the anti-spyware security profile
  - name: EMAIL_PROFILE_GATEWAY
    description: email gateway address for critical alerts
    default: 192.0.2.1
    type_hint: text
    help_text: email server profile configuration under Device --> Server Profiles
  - name: EMAIL_PROFILE_FROM
    description: from address in email alerts
    default: sentfrom@yourdomain.com
    type_hint: text
    help_text: email server profile configuration under Device --> Server Profiles
  - name: EMAIL_PROFILE_TO
    description: to address in email alerts
    default: sendto@yourdomain.com
    type_hint: text
    help_text: email server profile configuration under Device --> Server Profiles
  - name: SYSLOG_SERVER
    description: syslog server ip address
    default: 192.0.2.2
    type_hint: text
  - name: API_KEY_LIFETIME
    description: lifetime for the api key in minutes
    default: 525600
    type_hint: text
    help_text: sets the expiration period for generated API keys
# option built into the templates to ignore the panw published external dynamic lists security rules
# should ONLY be excluded based on licensing limitations outside of best practices
# when 'yes' (default) will include the EDL rule
  - name: INCLUDE_PAN_EDL
    description: include the predefined Palo Alto Networks external lists security rules
    default: 'no'
    type_hint: dropdown
    help_text: a valid threat license and content updates are required to access the panw external-lists used in the rules
    dd_list:
      - key: 'yes'
        value: 'yes'
      - key: 'no'
        value: 'no'

snippets:
  - name: panorama-full
    file: iron_skillet_panorama_full.xml

